[profile.default]
src = './contracts'
test = './test/contracts'
out = './out'
libs = ["node_modules"]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config